const PDFDocument = require("pdfkit");
const ExcelJS = require("exceljs");
const accountModel = require("../models/accountModel");
const path = require("path");
const fs = require("fs");

function money(value) {

    return `₹ ${Number(value || 0).toLocaleString("en-IN")}`;

}

function formatDate(date) {

    if (!date) return "";

    return new Date(date).toLocaleDateString("en-GB", {
        day: "2-digit",
        month: "short",
        year: "numeric"
    });

}
function drawFooter(doc) {

    const footerY = doc.page.height - 35;

    doc.save();

    doc.moveTo(40, footerY - 8)
        .lineTo(555, footerY - 8)
        .strokeColor("#cccccc")
        .lineWidth(1)
        .stroke();

    doc.font("Noto");
    doc.fontSize(9);
    doc.fillColor("#666666");

    doc.text(
        `Generated on : ${formatDate(new Date())}`,
        40,
        footerY,
        {
            lineBreak: false
        }
    );

    doc.text(
        "Generated by Mandal Management System",
        170,
        footerY,
        {
            width: 220,
            align: "center",
            lineBreak: false
        }
    );

    doc.text(
        `Page ${doc.page.number}`,
        490,
        footerY,
        {
            width: 60,
            align: "right",
            lineBreak: false
        }
    );

    doc.restore();
}


exports.exportPDF = async (req, res) => {

    try {



        const year = req.query.year || new Date().getFullYear();

        const income = await accountModel.getYearIncomeList(year);

        const expenses = await accountModel.getYearExpenseList(year);

        const totalIncome = await accountModel.getYearIncome(year);

        const totalExpense = await accountModel.getYearExpense(year);

        const balance = totalIncome - totalExpense;

        const doc = new PDFDocument({
            size: "A4",
            margin: 40,
            bufferPages: true
        });
        doc.registerFont(
            "Noto",
            path.join(__dirname, "../fonts/NotoSans-Bold.ttf")

        );

        doc.font("Noto");

        res.setHeader(
            "Content-Type",
            "application/pdf"
        );

        res.setHeader(
            "Content-Disposition",
            `attachment; filename=Accounts_${year}.pdf`
        );

        doc.pipe(res);
        doc.save();

        doc.rotate(-35, {
            origin: [300, 400]
        });

        doc.font("Noto")
            .fontSize(60)
            .fillColor("#f2f2f2")
            .opacity(0.15)
            .text(
                "SHREE GANESH MANDAL",
                60,
                350,
                {
                    align: "center"
                }
            );

        doc.restore();

        //================ LOGO =================

        const logo = path.join(
            __dirname,
            "../public/images/logo.png"
        );

        if (fs.existsSync(logo)) {

            doc.image(
                logo,
                40,
                25,
                {
                    width: 65
                }
            );

        }

        //================ HEADER =================

        doc
            .fillColor("#e65100")
            .font("Helvetica-Bold")
            .fontSize(24)
            .text(
                "SHREE GANESH MANDAL",
                120,
                35
            );

        doc
            .fillColor("#444")
            .fontSize(14)
            .font("Helvetica")
            .text(
                "Annual Financial Report",
                120,
                67
            );

        doc
            .fontSize(11)
            .text(
                `Financial Year : ${year}`,
                120,
                88
            );

        doc
            .moveTo(40, 115)
            .lineTo(555, 115)
            .lineWidth(2)
            .strokeColor("#ff6f00")
            .stroke();

        //================ SUMMARY BOX =================

        doc
            .roundedRect(
                40,
                135,
                515,
                120,
                8
            )
            .fillAndStroke(
                "#FFF8F0",
                "#ff9800"
            );

        doc
            .fillColor("#e65100")
            .font("Noto")
            .fontSize(17)
            .text(
                "FINANCIAL SUMMARY",
                55,
                148
            );

        doc
            .fillColor("black")
            .font("Noto")
            .fontSize(12);

        doc.text(
            "Total Income",
            60,
            182
        );

        doc.text(
            money(totalIncome),
            420,
            182,
            {
                width: 100,
                align: "right"
            }
        );

        doc.text(
            "Total Expense",
            60,
            202
        );

        doc.text(
            money(totalExpense),
            420,
            202,
            {
                width: 100,
                align: "right"
            }
        );

        doc.font("Noto");

        doc.text(
            "Closing Balance",
            60,
            222
        );

        doc.text(
            money(balance),
            420,
            222,
            {
                width: 100,
                align: "right"
            }
        );

        let y = 285;

        //================ INCOME TITLE =================

        doc
            .fillColor("#e65100")
            .font("Helvetica-Bold")
            .fontSize(16)
            .text(
                "INCOME DETAILS",
                40,
                y
            );

        y += 25;

        //================ TABLE HEADER =================

        doc
            .fillColor("#ffffff")
            .rect(40, y, 515, 24)
            .fill("#ff9800");

        doc
            .fillColor("white")
            .font("Helvetica-Bold")
            .fontSize(10);

        doc.text("Date", 50, y + 7);

        doc.text("Source", 120, y + 7);

        doc.text("Received From", 260, y + 7);

        doc.text("Amount", 470, y + 7);

        y += 24;

        doc.font("Noto");

        //================ INCOME ROWS =================

        income.forEach((item, index) => {

            // Auto Page Break
            if (y > 740) {

                doc.addPage();

                y = 50;

                doc
                    .fillColor("#ffffff")
                    .rect(40, y, 515, 24)
                    .fill("#ff9800");

                doc.fillColor("white");

                doc.font("Noto");

                doc.fontSize(10);

                doc.text("Date", 50, y + 7);

                doc.text("Source", 120, y + 7);

                doc.text("Received From", 260, y + 7);

                doc.text("Amount", 470, y + 7);

                y += 24;

                doc.font("Noto");

            }

            // Alternate Row Color

            if (index % 2 == 0) {
                doc.rect(40, y, 515, 22)
                    .fillAndStroke("#FFF8F0", "#dddddd");
            }

            // Border

            doc.rect(40, y, 515, 22)

                .stroke("#dddddd");

            doc.fillColor("black");

            doc.fontSize(9);

            doc.text(

                formatDate(item.income_date),

                50,

                y + 6

            );

            doc.text(

                item.source || "-",

                120,

                y + 6,

                {

                    width: 120

                }

            );

            doc.text(

                item.received_from || "-",

                260,

                y + 6,

                {

                    width: 150

                }

            );

            doc.text(

                money(item.amount),

                445,

                y + 6,

                {

                    width: 90,

                    align: "right"

                }

            );

            y += 22;

        });

        // Income Total

        y += 10;

        doc.font("Noto");

        doc.fontSize(11);

        doc.text(

            "Income Total",

            300,

            y

        );

        doc.text(

            money(totalIncome),

            440,

            y,

            {

                width: 100,

                align: "right"

            }

        );

        y += 40;

        //================ EXPENSE TITLE =================

        doc.fillColor("#e65100");

        doc.fontSize(16);

        doc.text(

            "APPROVED EXPENSE DETAILS",

            40,

            y

        );

        y += 25;
        //================ EXPENSE TABLE HEADER =================

        doc
            .fillColor("#ffffff")
            .rect(40, y, 515, 24)
            .fill("#d32f2f");

        doc.fillColor("white");

        doc.font("Noto");

        doc.fontSize(10);

        doc.text("Date", 50, y + 7);

        doc.text("Category", 120, y + 7);

        doc.text("Item", 250, y + 7);

        doc.text("Amount", 470, y + 7);

        y += 24;

        doc.font("Noto");

        //================ EXPENSE ROWS =================

        expenses.forEach((item, index) => {

            // Auto Page Break

            if (y > 740) {

                doc.addPage();

                y = 50;

                doc
                    .fillColor("#ffffff")
                    .rect(40, y, 515, 24)
                    .fill("#d32f2f");

                doc.fillColor("white");

                doc.font("Noto");

                doc.fontSize(10);

                doc.text("Date", 50, y + 7);

                doc.text("Category", 120, y + 7);

                doc.text("Item", 250, y + 7);

                doc.text("Amount", 470, y + 7);

                y += 24;

                doc.font("Noto");

            }

            if (index % 2 === 0) {

                doc.rect(40, y, 515, 22)

                    .fill("#fff5f5");

            }

            doc.rect(40, y, 515, 22)

                .stroke("#dddddd");

            doc.fillColor("black");

            doc.fontSize(9);

            doc.text(

                formatDate(item.expense_date),

                50,

                y + 6

            );

            doc.text(

                item.category || "-",

                120,

                y + 6,

                {

                    width: 110

                }

            );

            doc.text(

                item.item_name || "-",

                250,

                y + 6,

                {

                    width: 170

                }

            );

            doc.text(

                money(item.total),

                445,

                y + 6,

                {

                    width: 90,

                    align: "right"

                }

            );

            y += 22;

        });

        //================ TOTAL =================

        y += 10;

        doc.font("Noto");

        doc.fontSize(11);

        doc.text(

            "Expense Total",

            300,

            y

        );

        doc.text(

            money(totalExpense),

            440,

            y,

            {

                width: 100,

                align: "right"

            }

        );

        y += 35;

        //================ BALANCE BOX =================

        doc.roundedRect(

            300,

            y,

            255,

            45,

            6

        ).fillAndStroke(

            "#E8F5E9",

            "#4CAF50"

        );

        doc.fillColor("#1B5E20");

        doc.font("Noto");

        doc.fontSize(13);

        doc.text(

            "Closing Balance",

            315,

            y + 8

        );

        doc.text(

            money(balance),

            430,

            y + 8,

            {

                width: 110,

                align: "right"

            }

        );

        y += 90;

        //================ SIGNATURES =================

        const treasurerSign = path.join(__dirname, "../public/signatures/treasurer.png");
        const secretarySign = path.join(__dirname, "../public/signatures/secretary.png");
        const presidentSign = path.join(__dirname, "../public/signatures/president.png");

        y += 40;

        if (fs.existsSync(treasurerSign)) {
            doc.image(treasurerSign, 45, y, { width: 80 });
        }

        if (fs.existsSync(secretarySign)) {
            doc.image(secretarySign, 235, y, { width: 80 });
        }

        if (fs.existsSync(presidentSign)) {
            doc.image(presidentSign, 425, y, { width: 80 });
        }

        y += 45;

        doc.moveTo(40, y).lineTo(150, y).stroke();
        doc.moveTo(220, y).lineTo(330, y).stroke();
        doc.moveTo(410, y).lineTo(520, y).stroke();

        doc.font("Noto").fontSize(11);

        doc.text("Treasurer", 70, y + 5);
        doc.text("Secretary", 240, y + 5);
        doc.text("President", 435, y + 5);
        function drawFooter(doc) {

            const footerY = doc.page.height - 40;

            // Top line
            doc.moveTo(40, footerY - 8)
                .lineTo(555, footerY - 8)
                .strokeColor("#cccccc")
                .lineWidth(1)
                .stroke();

            doc.font("Noto");
            doc.fontSize(9);
            doc.fillColor("#666666");

            // Left
            doc.text(
                `Generated on : ${formatDate(new Date())}`,
                40,
                footerY
            );

            // Center
            doc.text(
                "Generated by Mandal Management System",
                170,
                footerY,
                {
                    width: 220,
                    align: "center"
                }
            );

            // Right
            doc.text(
                `Page ${doc.bufferedPageRange().start + doc.bufferedPageRange().count}`,
                490,
                footerY,
                {
                    width: 60,
                    align: "right"
                }
            );

        }


        const range = doc.bufferedPageRange();

        for (let i = range.start; i < range.start + range.count; i++) {

            doc.switchToPage(i);

            drawFooter(doc);

        }

        doc.end();
    } catch (err) {

        console.log(err);

        res.status(500).send(err.message);

    }

};

// ================= EXCEL =================

exports.exportExcel = async (req, res) => {

    try {

        const year = req.query.year || new Date().getFullYear();

        const workbook = new ExcelJS.Workbook();

        const sheet = workbook.addWorksheet("Accounts");

        sheet.columns = [
            { header: "Date", key: "date", width: 15 },
            { header: "Type", key: "type", width: 15 },
            { header: "Name", key: "name", width: 35 },
            { header: "Amount", key: "amount", width: 15 }
        ];

        const income = await accountModel.getYearIncomeList(year);

        income.forEach(i => {

            sheet.addRow({
                date: formatDate(i.income_date),
                type: "Income",
                name: i.source,
                amount: i.amount
            });

        });

        const expenses = await accountModel.getYearExpenseList(year);

        expenses.forEach(e => {

            sheet.addRow({
                date: formatDate(e.expense_date),
                type: "Expense",
                name: e.item_name,
                amount: e.total
            });

        });

        res.setHeader(
            "Content-Type",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        );

        res.setHeader(
            "Content-Disposition",
            `attachment; filename=Accounts_${year}.xlsx`
        );

        await workbook.xlsx.write(res);

        res.end();

    } catch (err) {

        console.log(err);

        res.status(500).send(err.message);

    }

};